### ISSUE TITLE
Not able to run the project gives error as permission denied

### ISSUE THREAD

**Issue by vinaymcp** [CMSgov/beneficiary-fhir-data#265]
Hello,

I am trying to compile the things, but seems like some of the resouces are located in amazon requires authentication, can you help on how to access those resources so that i can compile it successfully. 

Following is the process i have tried.

Below is the command i  tried to run 

mvn -X release:prepare release:perform

But i am getting below errors

gov.cms.bfd.pipeline.rif.extract.s3.DataSetMonitorIT.multipleDataSetsTest(DataSetMonitorIT.java:176)
[INFO] Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: Anonymous access is forbidden for this operation (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: C60B73952C273289; S3 Extended Request ID: Z2Rcjbyrv2c7g+AG4L4hTZMs4adCBWk+e3C0r97V+nhI3xSC0uIS/sWIXjTUr8gpDz1ZznBoh2A=)

Tests in error: 
[INFO]   DataSetMonitorIT.emptyBucketTest:57 » AmazonS3 Anonymous access is forbidden f...
[INFO]   DataSetMonitorIT.multipleDataSetsTest:176 Runtime com.amazonaws.services.s3.mo...
[INFO]   DataSetMonitorWorkerIT.emptyBucketTest:32 » AmazonS3 Anonymous access is forbi...
[INFO]   DataSetMonitorWorkerIT.multipleDataSetsTest:140 » AmazonS3 Anonymous access is...
[INFO]   DataSetMonitorWorkerIT.singleDataSetTest:68 » AmazonS3 Anonymous access is for...
[INFO]   DataSetMonitorWorkerIT.skipDataSetTest:231 » AmazonS3 Anonymous access is forb...
[INFO]   ManifestEntryDownloadTaskIT.testMD5ChkSum:110 AwsFailure com.amazonaws.service...

Can any one help me out.

Thank you

**Comment by keithdadkins** [comment]
Although this is a public repo, contributing to the BFD is for CMS-approved contributors only, not outside contributors. So things like Integration Tests will fail. Maybe try with `-DskipITs`

Crazy long response time I know, sorry! But we do not use github for issues. Thanks!
