### ISSUE TITLE
Possible STU3 Extension Bug

### ISSUE THREAD

**Issue by jawalonoski** [CMSgov/beneficiary-fhir-data#765]
I think that the `CcwCodebookVariable.CLM_POA_IND_SW1 ` should vary based on the specific Diagnosis Code.

For example,

- `CcwCodebookVariable.CLM_POA_IND_SW2`
- `CcwCodebookVariable.CLM_POA_IND_SW3`
- etc.

https://github.com/CMSgov/beneficiary-fhir-data/blob/4debe426147e77e6564586315def8a4a900a8be2/apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/stu3/providers/TransformerUtils.java#L381-L385

I believe this has been corrected in R4 (L436):

https://github.com/CMSgov/beneficiary-fhir-data/blob/4debe426147e77e6564586315def8a4a900a8be2/apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/DiagnosisUtilV2.java#L432-L437

**Comment by JeremyIR** [comment]
The requested changes will be implemented in: [BFD-2333](https://jira.cms.gov/browse/BFD-2333)
