### ISSUE TITLE
ExplanationOfBenefit FHIR R4 data missing 2 fields

### ISSUE THREAD

**Issue by ccorley** [CMSgov/beneficiary-fhir-data#804]
I am validating FHIR R4 data from the v2 CMS Blue Button 2.0 API sandbox environment using the Python fhir.resources lib and am seeing the following errors, which appear to be valid:
```
entry -> 0 -> resource -> insurance -> 0 -> __root__ -> focal
  field required (type=value_error.missing)
entry -> 0 -> resource -> provider
  field required (type=value_error.missing)
```
I get one set of these for every ExplanationOfBenefit resource returned in a bundle (10 for user BBUser02001, for example).

Based on the profile:
http://hl7.org/fhir/us/carin-bb/STU1.1/StructureDefinition-C4BB-ExplanationOfBenefit-Professional-NonClinician.html
these appear to be valid errors, as the EOB data returned does not include an insurance focal value, e.g.:
```
        "insurance": [
          {
            "coverage": {
              "reference": "Coverage/part-b--19990000002002"
            }
          }
        ],
```
and the EOB data includes providers, but only at the CareTeam level, not at the ExplanationOfBenefits.provider level.

Any help you can provide in clarifying this issue would be greatly appreciated.

**Comment by ccorley** [comment]
I see that contributions to beneficiary-fhir-data are limited to those inside CMS.  However, this is fixed in my fork: https://github.com/ccorley/beneficiary-fhir-data/pull/1.  We need these changes to use a Blue Button client with LinuxForHealth, which does FHIR R4 validation as a part of its connect API, so I'll keep an eye out for changes to the Blue Button sandbox environment. Meanwhile we may need to run our own bfd server.

**Comment by JeremyIR** [comment]
This has been resolved in [`BFD-1446`](https://jira.cms.gov/browse/BFD-1446). Closing issue
